<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <PackageId>Opsd</PackageId>
    <Version>0.1.0</Version>
    <Title>Opsd .NET library</Title>
    <Description>.NET client library for the Opsd API</Description>
    <Authors>Opsd contributors</Authors>
    <PackageLicenseExpression>MIT OR Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>opsd;api;client;sdk</PackageTags>
    <PackageProjectUrl>https://opsd.sh</PackageProjectUrl>
    <RepositoryUrl>https://github.com/opsd-sh/opsd-dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
    <None Include="../../LICENSE-APACHE" Pack="true" PackagePath="/" />
    <None Include="../../LICENSE-MIT" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>

